### ISSUE TITLE
Can't connect to kia Niro.

### ISSUE THREAD

**Issue by AbNetten** [gruijter/com.kia_hyundai#4]
Can't connect to kia Niro.

Error: Pairing failed: @EuropeController.login: [401] Unauthorized on [POST] https://prd.eu-ccapi.kia.com:8080/api/v1/user/language - "{\"errId\":\"39e27ddc-5ab8-49d4-a91f-0073eca15b78\",\"errCode\":\"4010\",\"errMsg\":\"Require authentication\"}\n"

Ab Netten.

**Comment by ghost** [comment]
Same here

**Comment by peterlangela** [comment]
Same here.

The Homey site indicates:
"NOTE: THIS APP ONLY WORKS ON HOMEY PRO 2024. It cannot be installed on a Homey Pro 2016/2019."

I have a "Homey Pro (Early 2023)"

So, i look likes Homey dropped Kia support on these Pro devices.

**Comment by DarkVillager** [comment]
Should be fixed due to [9987832](https://github.com/gruijter/com.kia_hyundai/commit/99878327ce595335c3d757256c11249f03e35696), can u (@AbNetten ) test?

**Comment by AbNetten** [comment]
Fixed !!!!!

Thanks.


-------- Oorspronkelijk bericht --------
Van: Dark_Ville ***@***.***>
Datum: 16-08-2025 12:47 (GMT+01:00)
Aan: "gruijter/com.kia_hyundai" ***@***.***>
Cc: AbNetten ***@***.***>, Mention ***@***.***>
Onderwerp: Re: [gruijter/com.kia_hyundai] Can't connect to kia Niro. (Issue #4)

[https://avatars.githubusercontent.com/u/42322979?s=20&v=4]DarkVillager left a comment (gruijter/com.kia_hyundai#4)<https://github.com/gruijter/com.kia_hyundai/issues/4#issuecomment-3193578365>

Should be fixed due to 9987832<https://github.com/gruijter/com.kia_hyundai/commit/99878327ce595335c3d757256c11249f03e35696>, can u ***@***.***<https://github.com/AbNetten> ) test?

**Comment by peterlangela** [comment]
I still have the samen problem on my Homey Pro (Early 2023):

Error: Pairing failed: @EuropeController.login: [401] Unauthorized on [POST] https://prd.eu-ccapi.kia.com:8080/api/v1/user/signin - {"errId":"819b9daa-5f57-4d80-93b6-a9d8d9ab6a33","errCode":"4010","errMsg":"Require authentication"}

**Comment by SolusVenator** [comment]
Error: Pairing failed:@AustraliaComtroler.getVehicles:[401]Unauthorized on [Get] https://au-apigw.ccs.kia.com.au:8082/api/v1/spa/vehicles {“retCode”:’F”,”resCode”:4017”,”resMsg”:”Invalid request value - Invalid Application Id.”,”msgld”:’f164cdf0-b2dc-11f0-95d0-ecd53c9e9892”} 

Similar issue with Australian server also I am using an ‘Early 2023’ Homey Pro Version 12.8.0 OS
